<?php

/**
 * @file
 * Contains visualn_examples.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function visualn_examples_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the visualn_examples module.
    case 'help.page.visualn_examples':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('VisualN misc examples') . '</p>';
      return $output;

    default:
  }
}
